n_masses: 10
r: 5
mass: 50
size: small
T: 288.20
body: pressure
brain: mlp
solver: cmaes
task: hilly-1-10
timesteps: 1800
mode: random
evaluations: 10000
seed: 0
np: 8
control_pressure: 1
save_video: 1