n_masses: 15
r: 7.5
mass: 75
size: medium
T: 288.20
body: pressure
brain: mlp
solver: cmaes
task: hilly-2-10
timesteps: 1800
mode: best
evaluations: 10000
seed: 2
np: 8
control_pressure: 1
save_video: 0