n_masses: 20
r: 10
mass: 100
size: large
T: 288.20
body: pressure
brain: mlp
solver: cmaes
task: hilly-3-10
timesteps: 1800
mode: opt-parallel
evaluations: 10000
seed: 0
np: 8
control_pressure: 1
control_joints: 1
save_video: 0